version: '3.5'

# 6100 - proxy
# 6101 - db

services:
  db:
    container_name: db
    restart: always
    ports:
      - "6101:6101"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.1-alpine
    #volumes:
    #  - db_vol:/var/lib/postgresql/data
    command: 
      - "postgres"
      - "-c"
      - "port=6101"
    networks:
      internal_net:
        ipv4_address: 172.20.0.5
    profiles: ["dev"]

  proxy:
    ports:
      - "6100:6100"
    container_name: proxy
    build: ./proxy
    restart: always
    environment:
      - PROXY_PORT=6100
      - HOST=172.20.0.5
      - PORT=6101
    depends_on:
      - db
    networks:
      internal_net:
        ipv4_address: 172.20.0.6
    profiles: ["dev"]

  postgres_sysbench:
    build: ./postgres_sysbench
    container_name: postgres_sysbench
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=root
      - DB_HOST=proxy
      - DB_PORT=6100
      - DB_NAME=postgres
      - SYSBENCH_THREAD=10
      - SYSBENCH_TIME=100
    command: 
      - "./run_sysbench.sh"
    networks:
      internal_net:
        ipv4_address: 172.20.0.7
    depends_on:
      - db
      - proxy
    links:
      - db
      - proxy
    profiles: ["dev"]

#volumes:
#  db_vol: {}


networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
